import 'package:flutter/cupertino.dart';

class Constants with ChangeNotifier {
  static const Map<String, String> quesAnd = {
    'Question 1,Lorem Ipsum is simply dummy text of the printing and typesetting industry.':
        "Answer1 Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia, mestiae quas vel sint commodi repudiandae consequuntur voluptatum laborumnumquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentiumoptio, eaque rerum! Provident similique accusantium nemo autem. Veritatisobcaecati tenetur iure eius earum ut molestias architecto voluptate aliquamnihil, eveniet aliquid culpa officia aut! Impedit sit sunt quaerat, odit,tenetur error, harum nesciunt ipsum debitis quas aliquid.",
    'Question 2 ,Lorem Ipsum simply dummy text of the printing and typesetting industry.':
        "Answer 2 Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia, mestiae quas vel sint commodi repudiandae consequuntur voluptatum laborumnumquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentiumoptio, eaque rerum! Provident similique accusantium nemo autem. Veritatisobcaecati tenetur iure eius earum ut molestias architecto voluptate aliquamnihil, eveniet aliquid culpa officia aut! Impedit sit sunt quaerat, odit,tenetur error, harum nesciunt ipsum debitis quas aliquid.",
    'Question 3, Lorem Ipsum is simply dummy text of the printing and typesetting industry.':
        "Answer 3 Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia, mestiae quas vel sint commodi repudiandae consequuntur voluptatum laborumnumquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentiumoptio, eaque rerum! Provident similique accusantium nemo autem. Veritatisobcaecati tenetur iure eius earum ut molestias architecto voluptate aliquamnihil, eveniet aliquid culpa officia aut! Impedit sit sunt quaerat, odit,tenetur error, harum nesciunt ipsum debitis quas aliquid.",
    'Question 4, Lorem Ipsum is simply dummy text of the printing and typesetting industry.':
        "Answer 4 Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia, mestiae quas vel sint commodi repudiandae consequuntur voluptatum laborumnumquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentiumoptio, eaque rerum! Provident similique accusantium nemo autem. Veritatisobcaecati tenetur iure eius earum ut molestias architecto voluptate aliquamnihil, eveniet aliquid culpa officia aut! Impedit sit sunt quaerat, odit,tenetur error, harum nesciunt ipsum debitis quas aliquid.",
    'Question 5, Lorem Ipsum is simply dummy text of the printing and typesetting industry.':
        "Answer 5 Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia, mestiae quas vel sint commodi repudiandae consequuntur voluptatum laborumnumquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentiumoptio, eaque rerum! Provident similique accusantium nemo autem. Veritatisobcaecati tenetur iure eius earum ut molestias architecto voluptate aliquamnihil, eveniet aliquid culpa officia aut! Impedit sit sunt quaerat, odit,tenetur error, harum nesciunt ipsum debitis quas aliquid.",
    'Question 6, Lorem Ipsum is simply dummy text of the printing and typesetting industry.':
        "Answer 6 Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia, mestiae quas vel sint commodi repudiandae consequuntur voluptatum laborumnumquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentiumoptio, eaque rerum! Provident similique accusantium nemo autem. Veritatisobcaecati tenetur iure eius earum ut molestias architecto voluptate aliquamnihil, eveniet aliquid culpa officia aut! Impedit sit sunt quaerat, odit,tenetur error, harum nesciunt ipsum debitis quas aliquid.",
    'Question 7, Lorem Ipsum is simply dummy text of the printing and typesetting industry.':
        "Answer 7 Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia, mestiae quas vel sint commodi repudiandae consequuntur voluptatum laborumnumquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentiumoptio, eaque rerum! Provident similique accusantium nemo autem. Veritatisobcaecati tenetur iure eius earum ut molestias architecto voluptate aliquamnihil, eveniet aliquid culpa officia aut! Impedit sit sunt quaerat, odit,tenetur error, harum nesciunt ipsum debitis quas aliquid.",
    'Question 8, Lorem Ipsum is simply dummy text of the printing and typesetting industry.':
        "Answer 8 Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia, mestiae quas vel sint commodi repudiandae consequuntur voluptatum laborumnumquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentiumoptio, eaque rerum! Provident similique accusantium nemo autem. Veritatisobcaecati tenetur iure eius earum ut molestias architecto voluptate aliquamnihil, eveniet aliquid culpa officia aut! Impedit sit sunt quaerat, odit,tenetur error, harum nesciunt ipsum debitis quas aliquid.",
  };
}
